import Head from 'next/head';
import React, { ReactFragment } from 'react';
import LayoutWrapper from './styles';

const Layout = ({children}: {children:ReactFragment}) => {
    return <LayoutWrapper>
        <Head>
        <title>Next TS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      {children}
      </main>
    </LayoutWrapper>
}

export default Layout;